"use client";

import { Sparkles, TrendingUp, TrendingDown, Minus, Eye } from "lucide-react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { AiPortfolioMove } from "@/types/ai";
import { DEMO_AI_INSIGHT, DEMO_MONTH_LABEL } from "@/components/landing/demo/sampleData";

// Static mirror of AiInsightPanel (which calls Claude via a hook). The landing
// page shows a pre-written analysis so visitors see the real output shape
// without an API call.

const ACTION_META: Record<
  AiPortfolioMove["action"],
  { label: string; className: string; Icon: React.ElementType }
> = {
  buy: { label: "Buy", className: "text-green-500", Icon: TrendingUp },
  hold: { label: "Hold", className: "text-muted-foreground", Icon: Minus },
  sell: { label: "Sell", className: "text-red-500", Icon: TrendingDown },
  watch: { label: "Watch", className: "text-yellow-500", Icon: Eye },
};

export function DemoAiInsights() {
  const insight = DEMO_AI_INSIGHT;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Sparkles className="size-4 text-primary" />
        Generated by Claude — sample analysis
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="border-border bg-card lg:col-span-2">
          <CardHeader>
            <CardTitle>The Roast</CardTitle>
            <CardDescription>{DEMO_MONTH_LABEL}</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-base leading-relaxed">{insight.roast}</p>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardHeader>
            <CardTitle className="text-positive">Wins</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              {insight.wins.map((item) => (
                <li key={item} className="rounded-lg bg-background/60 px-3 py-2">
                  {item}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardHeader>
            <CardTitle>Action Items</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              {insight.actions.map((item) => (
                <li key={item} className="rounded-lg bg-background/60 px-3 py-2">
                  {item}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardHeader>
            <CardTitle className="text-negative">Flagged</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              {insight.flagged.map((item) => (
                <li key={item} className="rounded-lg bg-background/60 px-3 py-2">
                  {item}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardHeader>
            <CardTitle>Goal Allocations</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              {Object.entries(insight.allocations).map(([goal, advice]) => (
                <li key={goal} className="rounded-lg bg-background/60 px-3 py-2">
                  <p className="font-medium">{goal}</p>
                  <p className="text-muted-foreground">{advice}</p>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {insight.portfolio ? (
          <Card className="border-border bg-card lg:col-span-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="size-4" />
                Portfolio Moves
              </CardTitle>
              <CardDescription>{insight.portfolio.summary}</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                {insight.portfolio.moves.map((move) => {
                  const meta = ACTION_META[move.action] ?? ACTION_META.hold;
                  const { Icon } = meta;
                  return (
                    <li
                      key={move.ticker}
                      className="flex items-start gap-3 rounded-lg bg-background/60 px-3 py-2.5"
                    >
                      <div className={`mt-0.5 shrink-0 ${meta.className}`}>
                        <Icon className="size-4" />
                      </div>
                      <div className="min-w-0">
                        <p className="flex items-baseline gap-1.5 text-sm">
                          <span className="font-mono font-semibold">{move.ticker}</span>
                          <span className={`text-xs font-medium ${meta.className}`}>{meta.label}</span>
                        </p>
                        <p className="mt-0.5 text-xs leading-snug text-muted-foreground">
                          {move.rationale}
                        </p>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </CardContent>
          </Card>
        ) : null}
      </div>
    </div>
  );
}
